# Generated by Django 4.1.5 on 2023-01-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envoyAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envoytable',
            name='Count',
            field=models.IntegerField(default=0),
        ),
    ]
